### ISSUE TITLE
MySQL gateway does not work with MySQLWorkbench

### ISSUE THREAD

**Issue by dclim** [implydata/plyql#24]
```
[2] Got SQL: set autocommit=1
[2] Got SQL: SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
[2] Got SQL: SHOW SESSION VARIABLES LIKE 'lower_case_table_names'
[2] Got SQL: SELECT current_user()

Failed to resolve query with Plywood.
Query:
SELECT current_user()
If you believe this query should work please create an issue on PlyQL and include this section
Issue url: https://github.com/implydata/plyql/issues
Message:
SQL parse error: Expected "*", "+", ",", "-", ".", "/", ";", "AND", "AS", "BETWEEN", "CONTAINS", "FROM", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "REGEXP", "WHERE", Comparison or end of input but "(" found. on 'SELECT current_user()'
Stack:
Error: SQL parse error: Expected "*", "+", ",", "-", ".", "/", ";", "AND", "AS", "BETWEEN", "CONTAINS", "FROM", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "REGEXP", "WHERE", Comparison or end of input but "(" found. on 'SELECT current_user()'
    at Function.Expression.parseSQL (/usr/local/lib/node_modules/plyql/node_modules/plywood/build/plywood.js:5482:23)
    at /usr/local/lib/node_modules/plyql/build/plyql-mysql-gateway.js:43:53
    at Promise.apply (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/plyql/node_modules/q/q.js:1391:14
    at runSingle (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

where: 

```
mysql> SELECT current_user();
+-----------------+
| current_user()  |
+-----------------+
| druid@localhost |
+-----------------+
1 row in set (0.00 sec)
```

**Comment by vogievetsky** [comment]
Yay an easy one :-)

**Comment by vogievetsky** [comment]
Just to clarify: making `SELECT current_user()` would be easy that will probably be done today but involved tools like MySQLWorkbench make a ton of fancy queries and each could derail the whole operation. It will take time and iteration before MySQLWorkbench works. We can keep track of progress here.

**Comment by vogievetsky** [comment]
Got past `current_user()` only to fail on `SHOW STATUS`

```
[1] Got SQL: set autocommit=1
[1] Got SQL: SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
[1] Got SQL: SHOW SESSION VARIABLES LIKE 'lower_case_table_names'
[1] Got SQL: SELECT current_user()
[1] Got SQL: SET CHARACTER SET utf8
[1] Got SQL: SET NAMES utf8
[1] Got SQL: SHOW SESSION VARIABLES LIKE 'sql_mode'
[1] Got SQL: SELECT CONNECTION_ID()
[1] Got SQL: SHOW SESSION STATUS LIKE 'Ssl_cipher'
```
