### ISSUE TITLE
MySQL gateway with Tableau (9.3) issue with TOPN queries

### ISSUE THREAD

**Issue by freakyzoidberg** [implydata/plyql#25]
Hi

Firstly, awesome work on providing this mysql gateway query pattern, this is very exciting.

Running into an issue when applying a Top N filter in tableau

Thanks

```
If you believe this query should work please create an issue on PlyQL and include this section
Issue url: https://github.com/implydata/plyql/issues
Message:
SQL parse error: Expected ".", ";", "GROUP", "HAVING", "LIMIT", "ORDER", "WHERE" or end of input but "I" found. on 'SELECT `DRUID`.`BRANCH` AS `BRANCH`
FROM `DRUID`
  INNER JOIN (
  SELECT `DRUID`.`BRANCH` AS `BRANCH`,
    COUNT(`DRUID`.`BRANCH`) AS `$__alias__0`
  FROM `DRUID`
  GROUP BY 1
  ORDER BY `$__alias__0` DESC
  LIMIT 10
) `t0` ON (`DRUID`.`BRANCH` <=> `t0`.`BRANCH`)
WHERE ((`DRUID`.`__time` >= TIMESTAMP('2016-04-24 00:00:00')) AND (`DRUID`.`__time` < TIMESTAMP('2016-05-06 00:00:00')))
GROUP BY 1'
Stack:
Error: SQL parse error: Expected ".", ";", "GROUP", "HAVING", "LIMIT", "ORDER", "WHERE" or end of input but "I" found. on 'SELECT `DRUID`.`BRANCH` AS `BRANCH`
FROM `DRUID`
  INNER JOIN (
  SELECT `DRUID`.`BRANCH` AS `BRANCH`,
    COUNT(`DRUID`.`BRANCH`) AS `$__alias__0`
  FROM `DRUID`
  GROUP BY 1
  ORDER BY `$__alias__0` DESC
  LIMIT 10
) `t0` ON (`DRUID`.`BRANCH` <=> `t0`.`BRANCH`)
WHERE ((`DRUID`.`__time` >= TIMESTAMP('2016-04-24 00:00:00')) AND (`DRUID`.`__time` < TIMESTAMP('2016-05-06 00:00:00')))
GROUP BY 1'
    at Function.Expression.parseSQL (/usr/local/lib/node_modules/plyql/node_modules/plywood/build/plywood.js:5482:23)
    at /usr/local/lib/node_modules/plyql/build/plyql-mysql-gateway.js:43:53
    at Promise.apply (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/plyql/node_modules/q/q.js:1391:14
    at runSingle (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/plyql/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by vogievetsky** [comment]
Thanks for submitting! Yeah `INNER JOIN` is a bitch. As a sidenote of curiosity: is your druid datasource called `"DRUID"` ?

**Comment by freakyzoidberg** [comment]
Yes :),

lack of imagination, that is from an experiment environment.

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
