### ISSUE TITLE
Mysql gateway not supporting show warning command

### ISSUE THREAD

**Issue by rajitha703** [implydata/plyql#30]
Hi,

Show warnings doesn't seem to be supported in the new Mysql gateway . Would be great if this can be supported in any of the future releases.  

Got SQL: SHOW WARNINGS

```
Failed to resolve query with Plywood.
Query:
SHOW WARNINGS
If you believe this query should work please create an issue on PlyQL and include this section
Issue url: https://github.com/implydata/plyql/issues
Message:
SQL parse error: Expected "COLUMNS", "DATABASES", "FULL", "GLOBAL", "SCHEMAS", "SESSION", "TABLES" or "VARIABLES" but "W" found. on 'SHOW WARNINGS'
Stack:
Error: SQL parse error: Expected "COLUMNS", "DATABASES", "FULL", "GLOBAL", "SCHEMAS", "SESSION", "TABLES" or "VARIABLES" but "W" found. on 'SHOW WARNINGS'
    at Function.Expression.parseSQL (/home/rajitha/imply-1.2.1/dist/pivot/node_modules/plywood/build/plywood.js:5482:23)
    at /home/rajitha/imply-1.2.1/dist/pivot/node_modules/plyql/build/plyql-mysql-gateway.js:43:53
    at Promise.apply (/home/rajitha/imply-1.2.1/dist/pivot/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/rajitha/imply-1.2.1/dist/pivot/node_modules/q/q.js:788:41)
    at /home/rajitha/imply-1.2.1/dist/pivot/node_modules/q/q.js:1391:14
    at runSingle (/home/rajitha/imply-1.2.1/dist/pivot/node_modules/q/q.js:137:13)
    at flush (/home/rajitha/imply-1.2.1/dist/pivot/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by vogievetsky** [comment]
good one!

**Comment by vogievetsky** [comment]
Will add support in future release

**Comment by rajitha703** [comment]
Sure. Thanks

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
