### ISSUE TITLE
not able to make connection using java code

### ISSUE THREAD

**Issue by justgig8** [implydata/plyql#67]
Below is the Plyql MySQL gateway log when I try to make a connection using com.mysql.jdbc.Driver through Java class:-

gauravmacbookpro:bin gaurav$ ./plyql -h localhost:8082 -i P2Y/2020-01-01 --experimental-mysql-gateway 3307
MySQL Gateway listening on port: 3307
New connection 1
[1] Got SQL: /* mysql-connector-java-5.1.6 ( Revision: ${svn.Revision} ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'init_connect'
[1] Got SQL: SHOW COLLATION
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Failed to resolve query with Plywood.
Query:
SHOW COLLATION
If you believe this query should work please create an issue on PlyQL and include this section
Issue url: https://github.com/implydata/plyql/issues
Message:
SQL parse error: Expected "COLUMNS", "DATABASES", "FULL", "GLOBAL", "SCHEMAS", "SESSION", "TABLES" or "VARIABLES" but "C" found. on 'SHOW COLLATION'
Stack:
Error: SQL parse error: Expected "COLUMNS", "DATABASES", "FULL", "GLOBAL", "SCHEMAS", "SESSION", "TABLES" or "VARIABLES" but "C" found. on 'SHOW COLLATION'
    at Function.Expression.parseSQL (/Users/gaurav/imply-1.3.0/dist/pivot/node_modules/plywood/build/plywood.js:5985:23)
    at /Users/gaurav/imply-1.3.0/dist/pivot/node_modules/plyql/build/plyql-mysql-gateway.js:43:53
    at Promise.apply (/Users/gaurav/imply-1.3.0/dist/pivot/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/Users/gaurav/imply-1.3.0/dist/pivot/node_modules/q/q.js:788:41)
    at /Users/gaurav/imply-1.3.0/dist/pivot/node_modules/q/q.js:1391:14
    at runSingle (/Users/gaurav/imply-1.3.0/dist/pivot/node_modules/q/q.js:137:13)
    at flush (/Users/gaurav/imply-1.3.0/dist/pivot/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1] Error: Connection lost: The server closed the connection.

**Comment by vogievetsky** [comment]
Need to add support for https://dev.mysql.com/doc/refman/5.7/en/collations-table.html

**Comment by vogievetsky** [comment]
`SHOW COLLATION` should now work in 0.9.14. Try again using newest version. Open new issue if there are further problems. :-D
