### ISSUE TITLE
Still Issue with SiSense BI Tools 

### ISSUE THREAD

**Issue by richiesgr** [implydata/plyql#73]
Hi

I've already open a ticket regarding this request 
SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1'

Where I try this query I get this
```
[7] Got SQL: SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Failed to resolve query with Plywood.
Query:
SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1'
If you believe this query should work please create an issue on PlyQL and include this section
Issue url: https://github.com/implydata/plyql/issues
Message:
SQL parse error: Expected "*", "+", "-", ".", "/", ";", "AND", "GROUP", "HAVING", "LIMIT", "OR", "ORDER" or end of input but "'" found. on 'SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1''
Stack:
Error: SQL parse error: Expected "*", "+", "-", ".", "/", ";", "AND", "GROUP", "HAVING", "LIMIT", "OR", "ORDER" or end of input but "'" found. on 'SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1''
    at Function.Expression.parseSQL (/home/ubuntu/imply-1.3.0/dist/pivot/node_modules/plywood/build/plywood.js:5985:23)
    at /home/ubuntu/imply-1.3.0/dist/pivot/node_modules/plyql/build/plyql-mysql-gateway.js:43:53
    at Promise.apply (/home/ubuntu/imply-1.3.0/dist/pivot/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/ubuntu/imply-1.3.0/dist/pivot/node_modules/q/q.js:788:41)
    at /home/ubuntu/imply-1.3.0/dist/pivot/node_modules/q/q.js:1391:14
    at runSingle (/home/ubuntu/imply-1.3.0/dist/pivot/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/imply-1.3.0/dist/pivot/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

could you help me ?

**Comment by vogievetsky** [comment]
that is so strange. I am running on the latest plyql and that query seems to work:

```
mysql> SELECT DISTINCT `TABLE_NAME`, `TABLE_TYPE`, (TABLE_SCHEMA) AS `TABLE_SCHEMA` FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` = N'plyql1';
+-------------------+------------+--------------+
| TABLE_NAME        | TABLE_TYPE | TABLE_SCHEMA |
+-------------------+------------+--------------+
| wikipedia         | BASE TABLE | plyql1       |
| wikipedia-compact | BASE TABLE | plyql1       |
+-------------------+------------+--------------+
2 rows in set (0.01 sec)
```

What version of plyql are you on? `plyql --version`

**Comment by richiesgr** [comment]
plyql version 0.9.14 (plywood version 0.15.7)

**Comment by richiesgr** [comment]
Hi

Reopening this because I've still problem to connect SiSense to Druid and now it's because that Sisense decide even for A table build on my own query to postfix it with "Limit 0,0"
So all requests with Limit 0,0 are not supported do you've any idea if I can find a workaround. Changing the behavior in Sisense is not a option As I've understand 

Thanks

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
