### ISSUE TITLE
error when trying to change heap size (plyql 0.10.7)

### ISSUE THREAD

**Issue by talJoffeExelate** [implydata/plyql#77]
following issue #62, I'm trying the exact same thing with plyql 0.10.7 and get the following error:

$ node --max-old-space-size=268435456 /usr/bin/plyql --host :8080 --experimental-mysql-gateway 3306

/usr/lib/node_modules/plyql/bin/plyql:3
if command -v node > /dev/null 2>&1; then
^^^^^^^
SyntaxError: Unexpected identifier
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:393:7)
at startup (bootstrap_node.js:150:9)

I tried several variations on this and can't figure out what is the problem. any help is much appreciated

**Comment by talJoffeExelate** [comment]
Figured it out..

Should have used it like this:
plyql --max-old-space-size=256m  --host <broker-ip>:8080 --experimental-mysql-gateway 3306
