### ISSUE TITLE
Latest row in druid's streaming datasource

### ISSUE THREAD

**Issue by nsaurabh777** [implydata/plyql#85]
I am using PlyQL to get the latest row in my streaming datasource.

Query: `SELECT * FROM PlansServicesStreaming WHERE __time=(SELECT MAX(__time) FROM PlansServicesStreaming)`

The above query works in MySQL environment but not on PlyQL. Any suggestions?

Error: 
```
Failed to resolve query with Plywood.
Query:
SELECT * FROM PlansServicesStreaming WHERE __time=(SELECT MAX(__time) FROM PlansServicesStreaming)
If you believe this query should work please create an issue on PlyQL and include this section
Issue url: https://github.com/implydata/plyql/issues
Message:
SQL parse error: Expected "*", "+", ",", "-", "/", "AND", "AS", "BETWEEN", "CONTAINS", "GROUP", "IN", "IS", "LIKE", "NOT", "OR", "REGEXP", "WHERE", "`", Comparison, or String but "F" found. on 'SELECT * FROM PlansServicesStreaming WHERE __time=(SELECT MAX(__time) FROM PlansServicesStreaming)'
Stack:
Error: SQL parse error: Expected "*", "+", ",", "-", "/", "AND", "AS", "BETWEEN", "CONTAINS", "GROUP", "IN", "IS", "LIKE", "NOT", "OR", "REGEXP", "WHERE", "`", Comparison, or String but "F" found. on 'SELECT * FROM PlansServicesStreaming WHERE __time=(SELECT MAX(__time) FROM PlansServicesStreaming)'
    at Function.Expression.parseSQL (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/plywood/build/plywood.js:3361:19)
    at /home/maker/imply-2.3.4/dist/imply-ui/node_modules/plyql/build/plyql-mysql-gateway.js:76:45
    at Connection.<anonymous> (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/plyql/build/mysql-gateway.js:79:13)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at ServerHandshake.dispatchCommands (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/vogievetsky-mysql2/lib/commands/server_handshake.js:96:18)
    at ServerHandshake.Command.execute (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/vogievetsky-mysql2/lib/commands/command.js:34:20)
    at Connection.handlePacket (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/vogievetsky-mysql2/lib/connection.js:247:28)
    at PacketParser.onPacket (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/vogievetsky-mysql2/lib/connection.js:91:65)
    at PacketParser.executeStart (/home/maker/imply-2.3.4/dist/imply-ui/node_modules/vogievetsky-mysql2/lib/packet_parser.js:42:12)
```

**Comment by gianm** [comment]
Hi @nsaurabh777, instead try: `SELECT * FROM PlansServicesStreaming ORDER BY __time DESC LIMIT 1`

**Comment by nsaurabh777** [comment]
Yes. That works! But I wanted to know if such nested queries work.

Also, I would like to know why COUNT_DISTINCT() gives value in decimal. 

For eg.

```
mysql> SELECT ConsumerProductID,count_distinct(ConsumerServiceRequestID) as cnt From PlansServicesStreaming GROUP BY ConsumerProductID ORDER BY cnt DESC LIMIT 5;

| ConsumerProductID | cnt                |
|-------------------|--------------------|
| ABC               | 3.0021994137521975 |
| DEF               | 3.0021994137521975 |
| GHI               | 3.0021994137521975 |
| JKL               | 3.0021994137521975 |
| MNO               | 2.000977198748901  |

```

Will this be solved

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
